package org.metadatacenter.csvpipeline;

import org.metadatacenter.csvpipeline.cedar.*;
import org.metadatacenter.csvpipeline.ont.ChoiceIriStrategy;
import org.metadatacenter.csvpipeline.ont.OntologyAcronymStrategy;
import org.metadatacenter.csvpipeline.ont.OntologyIriStrategy;
import org.metadatacenter.csvpipeline.ont.OntologyLabelStrategy;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.nio.file.Path;

/**
 * Matthew Horridge
 * Stanford Center for Biomedical Informatics Research
 * 2022-06-17
 */
@Configuration
public class CedarImporterConfiguration {

    @Value("${cedar-api-key:")
    private String cedarApiKey;

    @Value("${template-field-description:Generated by the REDCap Data Dictionary to CEDAR Template tool}")
    private String templateFieldDescription;

    @Value("${values-type:CLASSES}")
    private ValuesType valuesType;

    @Value("${output}")
    private String outputDirectory;

    @Bean
    TemplateFieldWriter templateFieldWriter(TemplateFieldGenerator templateFieldGenerator) {
        return new TemplateFieldWriter(templateFieldGenerator, Path.of(outputDirectory));
    }

    @Bean
    CedarValuesStrategy cedarValuesStrategy(OntologyLabelStrategy ontologyLabelStrategy,
                                            ChoiceIriStrategy choiceIriStrategy,
                                            OntologyIriStrategy ontologyIriStrategy,
                                            OntologyAcronymStrategy ontologyAcroymnStrategy) {
        return switch (valuesType) {
            case CLASSES -> new ValuesFromClassesListStrategy(ontologyLabelStrategy, choiceIriStrategy);
            case LITERALS -> new ValuesFromLiteralsListStrategy();
            case ONTOLOGY -> new ValuesFromOntologyStrategy(ontologyIriStrategy,
                                                            ontologyAcroymnStrategy,
                                                            ontologyLabelStrategy);
        };
    }

    @Bean
    TemplateFieldGenerator templateFieldGenerator(CedarValuesStrategy valuesStrategy) {
        return new TemplateFieldGenerator(valuesStrategy, templateFieldDescription);
    }

    @Bean
    TemplateFieldCedarImporter cedarImporter(TemplateFieldGenerator templateFieldGenerator) {
        return new TemplateFieldCedarImporter(cedarApiKey, templateFieldGenerator);
    }
}
