package org.metadatacenter.cedar.artifactLib;

import org.metadatacenter.artifacts.model.core.ElementSchemaArtifact;
import org.metadatacenter.cedar.api.CedarId;
import org.metadatacenter.cedar.csv.CedarCsvParser;
import org.springframework.stereotype.Component;

import java.net.URI;
import java.util.Optional;
import java.util.UUID;

@Component
public class ElementGenerator {
  private FieldGeneratorFactory fieldGeneratorFactory;

  public ElementGenerator(FieldGeneratorFactory fieldGeneratorFactory) {
    this.fieldGeneratorFactory = fieldGeneratorFactory;
  }

  public ElementSchemaArtifact generateElementSchemaArtifact(CedarCsvParser.Node node, String name, String description) {
    //Name or description could be passed in when build umbrella element
    //Otherwise, both of them are null
    if(description == null){
      description = node.getDescription();
    }
    if(name == null){
      name = node.getSchemaName();
    }
    final String jsonSchemaDescription = name + " element is generated by CEDAR CLI";
    var jsonLdId = CedarId.resolveTemplateElementId(UUID.randomUUID().toString());
    var builder = ElementSchemaArtifact.builder();

    for (var child : node.getChildNodes()) {
      if (child.isElement()) {
        var elementSchemaArtifact = generateElementSchemaArtifact(child, null, null);
        builder.withElementSchema(elementSchemaArtifact);
      } else if (child.isField()) {
        var fieldSchemaArtifact = fieldGeneratorFactory.generateFieldSchemaArtifact(child);
        builder.withFieldSchema(fieldSchemaArtifact);
      }
    }

//    buildWithIdentifier(builder, node.getFieldIdentifier());
    buildWithPropertyIri(builder, node.getPropertyIri());

    return builder
        .withName(name)
        .withDescription(description)
        .withJsonSchemaDescription(jsonSchemaDescription)
        .withIsMultiple(node.isMultiValued())
        .withJsonLdId(URI.create(jsonLdId.value()))
        .build();
  }

  private void buildWithIdentifier(ElementSchemaArtifact.Builder builder, Optional<String> identifier){
    identifier.ifPresent(builder::withSchemaOrgIdentifier);
  }

  private void buildWithPropertyIri(ElementSchemaArtifact.Builder builder, Optional<String> propertyIri){
    propertyIri.ifPresent(s -> builder.withPropertyUri(URI.create(s)));
  }
}
