package org.metadatacenter.cedar.artifactLib;

import org.metadatacenter.artifacts.model.core.FieldSchemaArtifact;
import org.metadatacenter.cedar.csv.CedarCsvParser;

public interface FieldGenerator {
  FieldSchemaArtifact generateFieldArtifactSchema(CedarCsvParser.Node node);

  default String getJsonSchemaDescription(CedarCsvParser.Node node){
    return node.getSchemaName() + " is generated by CEDAR CLI";
  }
}
