package org.metadatacenter.cedar.webapi;

import org.metadatacenter.cedar.api.CedarId;
import org.metadatacenter.cedar.io.CedarApiKey;
import org.metadatacenter.cedar.io.CedarApiRequest;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.Map;

/**
 * Matthew Horridge
 * Stanford Center for Biomedical Informatics Research
 * 2022-08-01
 */
@Component
public class CreateFolderRequest {

    private String baseUrl = "https://resource.metadatacenter.org";

    private final CedarWebClientFactory webClientFactory;

    public CreateFolderRequest(CedarWebClientFactory webClientFactory) {
        this.webClientFactory = webClientFactory;
    }

    public CreateFolderResponse send(CedarApiKey cedarApiKey,
                                     String folderName,
                                     CedarId parentFolder) {
        return webClientFactory.createWebClient(HttpMethod.POST,
                                         "/folders",
                                         cedarApiKey)
                        .bodyValue(Map.of(
                                "folderId", parentFolder.value(),
                                "name", folderName,
                                "description", "Generated by CEDARCLI"
                        ))
                        .retrieve()
                        .bodyToMono(CreateFolderResponse.class)
                        .block();
    }

}
