package org.metadatacenter.cedar.webapi;

import org.metadatacenter.cedar.api.CedarId;
import org.metadatacenter.cedar.io.CedarApiKey;
import org.springframework.http.HttpMethod;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;

/**
 * Matthew Horridge
 * Stanford Center for Biomedical Informatics Research
 * 2022-08-01
 */
@Component
public class CreateFolderRequest {

    private String baseUrl = "https://resource.metadatacenter.org";

    private final CedarWebClientFactory webClientFactory;

    public CreateFolderRequest(CedarWebClientFactory webClientFactory) {
        this.webClientFactory = webClientFactory;
    }

    public CreateFolderResponse send(CedarApiKey cedarApiKey,
                                     String folderName,
                                     CedarId parentFolder) {

        var body = new HashMap<String, String>();
        if(parentFolder != null) {
            body.put("folderId", parentFolder.value());
        }
        body.put("name", folderName);
        body.put("description", "Generated by CEDARCLI");
        return webClientFactory.createWebClient(HttpMethod.POST,
                                                "/folders",
                                                cedarApiKey)
                               .bodyValue(body)
                               .retrieve()
                               .bodyToMono(CreateFolderResponse.class)
                               .block();
    }

}
