package org.metadatacenter.cedar.webapi;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.metadatacenter.cedar.api.CedarId;

import java.util.List;

/**
 * Matthew Horridge
 * Stanford Center for Biomedical Informatics Research
 * 2022-08-01
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreateFolderResponse(@JsonProperty("@id") CedarId id,
                                   @JsonProperty("schema:name") String schemaName,
                                   @JsonProperty("schema:description") String schemaDescription,
                                   @JsonProperty("pathInfo") List<CedarFolderResource> pathInfo) {

    /*

    {
	"resourceType": "folder",
	"path": null,
	"parentPath": null,
	"everybodyPermission": null,
	"homeOf": null,
	"isSystem": false,
	"isRoot": false,
	"isUserHome": false,
	"schema:name": "my-api-folder",
	"schema:description": "Generated by CEDARCLI",
	"pathInfo": [
		{
			"resourceType": "folder",
			"activeUserCanRead": false,
			"everybodyPermission": null,
			"isSystem": true,
			"isRoot": true,
			"isUserHome": false,
			"@id": "https://repo.metadatacenter.net/folders/6068bfc0-b3d8-47aa-8f11-51d806c9cbdd",
			"ownedBy": "https://metadatacenter.org/users/30449a1f-80a8-4b54-a3fa-92d4d6157116",
			"ownedByUserName": null,
			"pav:createdBy": "https://metadatacenter.org/users/30449a1f-80a8-4b54-a3fa-92d4d6157116",
			"oslc:modifiedBy": "https://metadatacenter.org/users/30449a1f-80a8-4b54-a3fa-92d4d6157116",
			"createdByUserName": null,
			"lastUpdatedByUserName": null,
			"schema:name": "/",
			"schema:description": "CEDAR Root Folder",
			"schema:identifier": null,
			"pav:createdOn": "2016-09-09T16:40:03-07:00",
			"pav:lastUpdatedOn": "2016-09-09T16:40:03-07:00",
			"sourceHash": null
		},
		{
			"resourceType": "folder",
			"activeUserCanRead": false,
			"everybodyPermission": null,
			"isSystem": true,
			"isRoot": false,
			"isUserHome": false,
			"@id": "https://repo.metadatacenter.net/folders/20f6f4f9-2210-4c0a-afe7-8496f3948ad6",
			"ownedBy": "https://metadatacenter.org/users/30449a1f-80a8-4b54-a3fa-92d4d6157116",
			"ownedByUserName": null,
			"pav:createdBy": "https://metadatacenter.org/users/30449a1f-80a8-4b54-a3fa-92d4d6157116",
			"oslc:modifiedBy": "https://metadatacenter.org/users/30449a1f-80a8-4b54-a3fa-92d4d6157116",
			"createdByUserName": null,
			"lastUpdatedByUserName": null,
			"schema:name": "Users",
			"schema:description": "CEDAR Users",
			"schema:identifier": null,
			"pav:createdOn": "2016-09-09T16:40:03-07:00",
			"pav:lastUpdatedOn": "2016-09-09T16:40:03-07:00",
			"sourceHash": null
		},
		{
			"resourceType": "folder",
			"activeUserCanRead": true,
			"everybodyPermission": null,
			"isSystem": false,
			"isRoot": false,
			"isUserHome": true,
			"@id": "https://repo.metadatacenter.org/folders/4938c321-5599-4205-87b7-d05eab1242f7",
			"ownedBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
			"ownedByUserName": null,
			"pav:createdBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
			"oslc:modifiedBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
			"createdByUserName": null,
			"lastUpdatedByUserName": null,
			"schema:name": "Matthew Horridge",
			"schema:description": "Home folder of Matthew Horridge",
			"schema:identifier": null,
			"pav:createdOn": "2022-03-10T14:23:35-08:00",
			"pav:lastUpdatedOn": "2022-03-10T14:23:35-08:00",
			"sourceHash": null
		},
		{
			"resourceType": "folder",
			"activeUserCanRead": true,
			"everybodyPermission": null,
			"isSystem": false,
			"isRoot": false,
			"isUserHome": false,
			"@id": "https://repo.metadatacenter.org/folders/d7e7292b-e751-4d22-93ef-804883733945",
			"ownedBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
			"ownedByUserName": null,
			"pav:createdBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
			"oslc:modifiedBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
			"createdByUserName": null,
			"lastUpdatedByUserName": null,
			"schema:name": "my-api-folder",
			"schema:description": "Generated by CEDARCLI",
			"schema:identifier": null,
			"pav:createdOn": "2022-08-01T16:20:45-07:00",
			"pav:lastUpdatedOn": "2022-08-01T16:20:45-07:00",
			"sourceHash": null
		}
	],
	"ownedBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
	"ownedByUserName": null,
	"schema:identifier": null,
	"pav:createdBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
	"oslc:modifiedBy": "https://metadatacenter.org/users/819b3cfd-49a9-4e72-b5d5-18166366f014",
	"createdByUserName": null,
	"lastUpdatedByUserName": null,
	"@id": "https://repo.metadatacenter.org/folders/d7e7292b-e751-4d22-93ef-804883733945",
	"@context": {
		"schema": "http://schema.org/",
		"pav": "http://purl.org/pav/",
		"bibo": "http://purl.org/ontology/bibo/",
		"oslc": "http://open-services.net/ns/core#"
	},
	"lastUpdatedOnTS": 1659396045,
	"createdOnTS": 1659396045,
	"pav:createdOn": "2022-08-01T16:20:45-07:00",
	"pav:lastUpdatedOn": "2022-08-01T16:20:45-07:00",
	"sourceHash": null
}

     */
}
