package org.metadatacenter.cedar.redcap;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.metadatacenter.cedar.csv.NumericBoundParser;
import org.metadatacenter.cedar.io.CedarArtifactWriter;
import org.metadatacenter.cedar.io.CedarArtifactPoster;
import org.metadatacenter.cedar.ont.ChoiceIriStrategy;
import org.metadatacenter.cedar.ont.OntologyAcronymStrategy;
import org.metadatacenter.cedar.ont.OntologyIriStrategy;
import org.metadatacenter.cedar.ont.OntologyLabelStrategy;
import org.metadatacenter.cedar.redcap.*;
import org.metadatacenter.cedar.webapi.CedarWebClientFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.inject.Named;
import java.nio.file.Path;

/**
 * Matthew Horridge
 * Stanford Center for Biomedical Informatics Research
 * 2022-06-17
 */
@Configuration
public class CedarImporterConfiguration {

    @Value("${template-field-description:Generated by the REDCap Data Dictionary to CEDAR Template tool}")
    private String templateFieldDescription;

    @Value("${values-type:CLASSES}")
    private ValuesType valuesType;

    @Bean
    TemplateFieldWriter templateFieldWriter(TemplateFieldGenerator templateFieldGenerator) {
        String outputDirectory = "";
        return new TemplateFieldWriter(templateFieldGenerator, Path.of(outputDirectory));
    }

    @Bean
    CedarValuesStrategy cedarValuesStrategy(OntologyLabelStrategy ontologyLabelStrategy,
                                            ChoiceIriStrategy choiceIriStrategy,
                                            OntologyIriStrategy ontologyIriStrategy,
                                            OntologyAcronymStrategy ontologyAcroymnStrategy) {
        return switch (valuesType) {
            case CLASSES -> new ValuesFromClassesListStrategy(ontologyLabelStrategy, choiceIriStrategy);
            case LITERALS -> new ValuesFromLiteralsListStrategy();
            case ONTOLOGY -> new ValuesFromOntologyStrategy(ontologyIriStrategy,
                                                            ontologyAcroymnStrategy,
                                                            ontologyLabelStrategy);
        };
    }

    @Bean
    TemplateFieldGenerator templateFieldGenerator(CedarValuesStrategy valuesStrategy, NumericBoundParser numericBoundParser) {
        return new TemplateFieldGenerator(valuesStrategy, templateFieldDescription, numericBoundParser);
    }

    @Bean
    NumericBoundParser numericBoundParser() {
        return new NumericBoundParser();
    }

    @Bean
    CedarArtifactPoster cedarImporter(CedarArtifactWriter artifactWriter,
                                      ObjectMapper objectMapper,
                                      CedarWebClientFactory factory) {
        objectMapper.registerModule(new JavaTimeModule());
        return new CedarArtifactPoster(artifactWriter, objectMapper, factory);
    }

    @Bean
    @Named("outputMapper")
    JsonMapper jsonMapper() {
        return JsonMapper.builder()
                         .configure(JsonGenerator.Feature.IGNORE_UNKNOWN, true)
                         .addModule(new JavaTimeModule())
                         .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
                         .build();
    }

    @Bean
    CedarArtifactWriter cedarArtifactWriter(@Named("outputMapper") JsonMapper jsonMapper) {
        return new CedarArtifactWriter(jsonMapper);
    }
}
